#📌 Extracción

In [21]:
# Importar las librerías necesarias
import pandas as pd
import requests

# URL del archivo JSON en GitHub
url = 'https://raw.githubusercontent.com/ingridcristh/challenge2-data-science-LATAM/main/TelecomX_Data.json'
# Realizar la solicitud HTTP para obtener los datos
request = requests.get(url)
# Convertir la respuesta JSON a un diccionario Python
data = request.json()
# Crear un DataFrame de pandas a partir de los datos
df = pd.DataFrame(data)
# Mostrar las primeras filas del DataFrame para una vista previa
df.head()

,customerID,Churn,customer,phone,internet,account
0,0002-ORFBO,No,"{'gender': 'Female', 'SeniorCitizen': 0, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'One year', 'PaperlessBilling': '..."
1,0003-MKNFE,No,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'Yes'}","{'InternetService': 'DSL', 'OnlineSecurity': '...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
2,0004-TLHLJ,Yes,"{'gender': 'Male', 'SeniorCitizen': 0, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
3,0011-IGKFF,Yes,"{'gender': 'Male', 'SeniorCitizen': 1, 'Partne...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."
4,0013-EXCHZ,Yes,"{'gender': 'Female', 'SeniorCitizen': 1, 'Part...","{'PhoneService': 'Yes', 'MultipleLines': 'No'}","{'InternetService': 'Fiber optic', 'OnlineSecu...","{'Contract': 'Month-to-month', 'PaperlessBilli..."

In [22]:
# Mostrar información general del DataFrame, incluyendo tipos de datos y valores no nulos
df.info()
# Mostrar los tipos de datos de cada columna
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   customerID  7267 non-null   object
 1   Churn       7267 non-null   object
 2   customer    7267 non-null   object
 3   phone       7267 non-null   object
 4   internet    7267 non-null   object
 5   account     7267 non-null   object
dtypes: object(6)
memory usage: 340.8+ KB

customerID    object
Churn         object
customer      object
phone         object
internet      object
account       object
dtype: object

In [23]:
# Normalizar las columnas anidadas (diccionarios) en DataFrames separados
# Extraer la información de 'customer' en un nuevo DataFrame
customer_df = pd.json_normalize(df['customer'])
# Extraer la información de 'phone' en un nuevo DataFrame
phone_df = pd.json_normalize(df['phone'])
# Extraer la información de 'internet' en un nuevo DataFrame
internet_df = pd.json_normalize(df['internet'])
# Extraer la información de 'account' en un nuevo DataFrame
account_df = pd.json_normalize(df['account'])

In [24]:
# Concatenar los nuevos DataFrames con el DataFrame original
# Eliminar las columnas anidadas originales y añadir las columnas normalizadas
df = pd.concat([df.drop(columns=['customer', 'phone', 'internet', 'account']), customer_df, phone_df, internet_df, account_df], axis=1)

# Mostrar la información del DataFrame actualizado
df.info()
# Mostrar las primeras filas del DataFrame actualizado
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.2+ MB

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.3
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.4
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.4

In [25]:
# Reemplazar los valores vacíos en la columna 'Churn' por 'No'
df['Churn'] = df['Churn'].replace({'': 'No'})

# Iterar sobre las columnas de tipo 'object' (categóricas) para mostrar sus valores únicos
for column in df.select_dtypes(include='object').columns:
    if column != 'customerID':  # Excluir 'customerID' ya que es un identificador
        print(f"Valores únicos para '{column}': {df[column].unique()}")
        print("\n")

Valores únicos para 'Churn': ['No' 'Yes']


Valores únicos para 'gender': ['Female' 'Male']


Valores únicos para 'Partner': ['Yes' 'No']


Valores únicos para 'Dependents': ['Yes' 'No']


Valores únicos para 'PhoneService': ['Yes' 'No']


Valores únicos para 'MultipleLines': ['No' 'Yes' 'No phone service']


Valores únicos para 'InternetService': ['DSL' 'Fiber optic' 'No']


Valores únicos para 'OnlineSecurity': ['No' 'Yes' 'No internet service']


Valores únicos para 'OnlineBackup': ['Yes' 'No' 'No internet service']


Valores únicos para 'DeviceProtection': ['No' 'Yes' 'No internet service']


Valores únicos para 'TechSupport': ['Yes' 'No' 'No internet service']


Valores únicos para 'StreamingTV': ['Yes' 'No' 'No internet service']


Valores únicos para 'StreamingMovies': ['No' 'Yes' 'No internet service']


Valores únicos para 'Contract': ['One year' 'Month-to-month' 'Two year']


Valores únicos para 'PaperlessBilling': ['Yes' 'No']


Valores únicos para 'PaymentMethod': ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']


Valores únicos para 'Charges.Total': ['593.3' '542.4' '280.85' ... '742.9' '4627.65' '3707.6']

#🔧 Transformación

In [26]:
# Convertir la columna 'Charges.Total' a tipo numérico, forzando errores a NaN
df['Charges.Total'] = pd.to_numeric(df['Charges.Total'], errors='coerce')
# Rellenar los valores NaN (generados por la conversión) con la media de la columna
df['Charges.Total'].fillna(df['Charges.Total'].mean(), inplace=True)
# Mostrar información general del DataFrame para verificar los tipos de datos
df.info()
# Mostrar las primeras filas del DataFrame
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   object
 2   gender            7267 non-null   object
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   object
 5   Dependents        7267 non-null   object
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   object
 8   MultipleLines     7267 non-null   object
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   object
 11  OnlineBackup      7267 non-null   object
 12  DeviceProtection  7267 non-null   object
 13  TechSupport       7267 non-null   object
 14  StreamingTV       7267 non-null   object
 15  StreamingMovies   7267 non-null   object
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   object
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   float64
dtypes: float64(2), int64(2), object(17)
memory usage: 1.2+ MB

/tmp/ipython-input-3437004258.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Charges.Total'].fillna(df['Charges.Total'].mean(), inplace=True)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,Yes,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,No,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40

In [27]:
# Verificar si hay valores ausentes en cada columna
print("Valores ausentes por columna:")
display(df.isnull().sum())

Valores ausentes por columna:

customerID          0
Churn               0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
Charges.Monthly     0
Charges.Total       0
dtype: int64

### Consistencia de categorías: Unificando 'No phone service' y 'No internet service'

Para asegurar la coherencia en las columnas categóricas que representan la disponibilidad de servicios, vamos a unificar los valores 'No phone service' y 'No internet service' a simplemente 'No'. Esto simplifica las categorías y facilita el análisis posterior, ya que en ambos casos, el cliente no tiene el servicio en cuestión.

In [28]:
# Verificar el número de filas duplicadas en el DataFrame
duplicates = df.duplicated().sum()
print(f"Número de filas duplicadas: {duplicates}")

# Si hay duplicados, mostrar las primeras 5 filas duplicadas
if duplicates > 0:
    print("\nMostrando las primeras 5 filas duplicadas (si las hay):")
    display(df[df.duplicated(keep=False)].head())

Número de filas duplicadas: 0

In [20]:
# Reemplazar 'No phone service' por 'No' en la columna 'MultipleLines'
df['MultipleLines'] = df['MultipleLines'].replace('No phone service', 'No')

# Definir las columnas relacionadas con el servicio de internet
internet_service_cols = ['OnlineSecurity', 'OnlineBackup', 'DeviceProtection',
                         'TechSupport', 'StreamingTV', 'StreamingMovies']

# Iterar sobre las columnas de servicio de internet y reemplazar 'No internet service' por 'No'
for col in internet_service_cols:
    df[col] = df[col].replace('No internet service', 'No')

# Imprimir los valores únicos de todas las columnas de tipo 'object' después de la unificación
print("Valores únicos después de la unificación:")
for column in df.select_dtypes(include='object').columns:
    if column != 'customerID':
        print(f"'{column}': {df[column].unique()}")

Valores únicos después de la unificación:
'Churn': ['No' 'Yes']
'gender': ['Female' 'Male']
'Partner': ['Yes' 'No']
'Dependents': ['Yes' 'No']
'PhoneService': ['Yes' 'No']
'MultipleLines': ['No' 'Yes']
'InternetService': ['DSL' 'Fiber optic' 'No']
'OnlineSecurity': ['No' 'Yes']
'OnlineBackup': ['Yes' 'No']
'DeviceProtection': ['No' 'Yes']
'TechSupport': ['Yes' 'No']
'StreamingTV': ['Yes' 'No']
'StreamingMovies': ['No' 'Yes']
'Contract': ['One year' 'Month-to-month' 'Two year']
'PaperlessBilling': ['Yes' 'No']
'PaymentMethod': ['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']

In [29]:
# Crear la columna 'Cuentas_Diarias' (Daily Charges)
# Se calcula dividiendo la facturación mensual por un promedio de 30 días para obtener un valor diario.
df['Cuentas_Diarias'] = df['Charges.Monthly'] / 30

# Mostrar las primeras filas del DataFrame con la nueva columna
print("DataFrame con la nueva columna 'Cuentas_Diarias':")
display(df.head())

DataFrame con la nueva columna 'Cuentas_Diarias':

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_Diarias
0,0002-ORFBO,No,Female,0,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,No,Male,0,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,Yes,Male,0,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,Yes,Male,1,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,Yes,Female,1,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,83.9,267.40,2.796667

### Estandarización de categorías binarias

Para facilitar el análisis y la modelización, se convertirán las columnas con valores 'Yes'/'No' y 'Male'/'Female' a un formato binario (1 y 0).

In [31]:
# Importar numpy para la conversión condicional
import numpy as np

# Columnas a convertir de 'Yes'/'No' a 1/0
columns_to_binary = [
    'Churn', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines',
    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
    'StreamingTV', 'StreamingMovies', 'PaperlessBilling'
]

for col in columns_to_binary:
    df[col] = np.where(df[col] == 'Yes', 1, 0)

# Convertir 'gender': 'Male' a 1, 'Female' a 0
df['gender'] = np.where(df['gender'] == 'Male', 1, 0)

print("Valores únicos después de la estandarización (binaria):")
for column in columns_to_binary:
    print(f"'{column}': {df[column].unique()}")
print(f"'gender': {df['gender'].unique()}")

# Mostrar la información general del DataFrame para verificar los tipos de datos
df.info()
# Mostrar las primeras filas del DataFrame actualizado
display(df.head())

Valores únicos después de la estandarización (binaria):
'Churn': [0]
'Partner': [0]
'Dependents': [0]
'PhoneService': [0]
'MultipleLines': [0]
'OnlineSecurity': [0]
'OnlineBackup': [0]
'DeviceProtection': [0]
'TechSupport': [0]
'StreamingTV': [0]
'StreamingMovies': [0]
'PaperlessBilling': [0]
'gender': [0]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7267 entries, 0 to 7266
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7267 non-null   object
 1   Churn             7267 non-null   int64
 2   gender            7267 non-null   int64
 3   SeniorCitizen     7267 non-null   int64
 4   Partner           7267 non-null   int64
 5   Dependents        7267 non-null   int64
 6   tenure            7267 non-null   int64
 7   PhoneService      7267 non-null   int64
 8   MultipleLines     7267 non-null   int64
 9   InternetService   7267 non-null   object
 10  OnlineSecurity    7267 non-null   int64
 11  OnlineBackup      7267 non-null   int64
 12  DeviceProtection  7267 non-null   int64
 13  TechSupport       7267 non-null   int64
 14  StreamingTV       7267 non-null   int64
 15  StreamingMovies   7267 non-null   int64
 16  Contract          7267 non-null   object
 17  PaperlessBilling  7267 non-null   int64
 18  PaymentMethod     7267 non-null   object
 19  Charges.Monthly   7267 non-null   float64
 20  Charges.Total     7267 non-null   float64
 21  Cuentas_Diarias   7267 non-null   float64
dtypes: float64(3), int64(15), object(4)
memory usage: 1.2+ MB

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total,Cuentas_Diarias
0,0002-ORFBO,0,0,0,0,0,9,0,0,DSL,...,0,0,0,0,One year,0,Mailed check,65.6,593.30,2.186667
1,0003-MKNFE,0,0,0,0,0,9,0,0,DSL,...,0,0,0,0,Month-to-month,0,Mailed check,59.9,542.40,1.996667
2,0004-TLHLJ,0,0,0,0,0,4,0,0,Fiber optic,...,0,0,0,0,Month-to-month,0,Electronic check,73.9,280.85,2.463333
3,0011-IGKFF,0,0,1,0,0,13,0,0,Fiber optic,...,0,0,0,0,Month-to-month,0,Electronic check,98.0,1237.85,3.266667
4,0013-EXCHZ,0,0,1,0,0,3,0,0,Fiber optic,...,0,0,0,0,Month-to-month,0,Mailed check,83.9,267.40,2.796667

#📊 Carga y análisis

#📄Informe final